### ISSUE TITLE
[bootloader 2.0] non sempre avviene il salto a boot

### ISSUE THREAD

**Issue by fgalfa** [alfa-sw/sw-programmazione-schede#12]
In presenza di slaves, il jump a volte non avviene.
Il dialogo è corretto, ed infatti status_level -> 9
Tuttavia la procedura non porta l'USB a diventare disponibile.

> [2021-10-18 15:44:05,831]INFO _observe_events() userlevel.py:495 Event label: EventLabel.ANSWER_RECV, Attachment: Answer node_id:200 cmd_code:MACHINE_STATUS, params:{'status_level': 9, 'cycle_step': 5, 'error_code': 2, 'cover_reserve': b'\x00', 'cover_availability': b'\x00', 'cover_enabled': b'\x00', 'container_reserve': b'\x00', 'container_availability': b'\x00', 'container_enabled': b'\x00', 'color_reserve': b'\x00\x00\x00\x00', 'container_presence': False, 'autocap_status': True, 'canlift_status': False, 'doors_status': False, 'clamp_position': 0, 'recirculation_status': b'\x00\x00\x00\x00', 'stirring_status': b'\x00\x00\x00\x00', 'slave_status': b'\x00\x00\x00\x00\x00\x00', 'can_on_plate': False, 'can_lifter_current_height': 0, 'can_lifter_range': 0, 'current_temperature': 65535, 'current_rel_humidity': 65535, 'water_level': False, 'critical_temperature': False, 'temperature': 65535, 'bases_carriage': True, 'circuit_engaged': 0, 'table_steps_position': 65535, 'autotest_cycles_number': 0, 'table_cleaning_status': b'\x00\x00\x00\x00', 'panel_table_status': True, 'photocells_status': 255, 'can_available': False, 'mixer_door_status': False, 'slave_enable_mask': b'\x80\x00\x00\x00\x00\x00', 'jar_photocells_status': 0, 'stop_formula': 0, 'punct_cleaning_proc': False, 'punct_recirc_proc': False, 'punctual_stirr_proc': False, 'refill_proc': False, 'dispensing_proc': False, 'cleaning_after_proc': False, 'temp_recirc_proc': False, 'reset_proc': False, 'temp_controll_proc': False, 'jar_pos_proc': False, 'eeprom_proc': False, 'pos_proc': False, 'self_rec_proc': False, 'crx_outputs_status': 0}, pending_cmd Source: <mab_serial_lib.lowlevel.LLProtocol object at 0x7fd8d7384e50>

Ripetendo la procedura più volte, anche senza riaccendere, il salto avviene.

**Comment by fgalfa** [comment]
A seguito di ulteriori indagini si è verificato che il problema si verifica anche in assenza di slaves collegate.

**Comment by micheleabelli** [comment]
Alla luce delle ultima modifiche nella sequenza logica di comandi che portano ad inviare il cmd "JUMP_TO_BOOT" e alle modifiche lato FW Applicativo MAB (MMT) che inibiscono il ritorno allo stato di 'Alarm' dopo l'invio di questo comando, il salto viene sempre effettuato
