### ISSUE TITLE
[bootloader 2.0] Modifica comando USB e proposta versionamento bootloader

### ISSUE THREAD

**Issue by fgalfa** [alfa-sw/sw-programmazione-schede#2]
La nuova versione di bootloader prevede nuovi comandi, tra cui il nuovo comando _BOOT_FW_VERSION_REQUEST_ per conoscere la versione di firmware. Eseguire questo comando nelle versioni precedenti risulta in un I/O error e nel blocco della scheda fino a successivo riavvio manuale. Per risolvere la problematica si propone di usare il comando QUERY già presente nelle precedenti versioni, e di modificare il payload in questo modo: sfruttare i 3 byte successivi al dato denominato _marker_ per inserire la versione di bootloader. Questi byte sono settati a 0 nelle versioni di boot attuali e la modifica non dovrebbe compromettere la funzionalità dell'aggiornatore legacy (da verificare.)

Si propone inoltre di cambiare il major number da 1 a 2. In questo modo il programma di aggiornamento sa che è cambiato il protocollo di comunicazione USB semplicemente facendo un check su questo numero (altrimenti bisogna memorizzare i numeri di versione di boot che differiscono a seconda della tipologia di scheda!)

**Comment by giovanni-angeli** [comment]
Ciao Giuliano,

tra ieri ed oggi ho iniziato a esaminare/valutare le modifiche che mi chiedevi nel doc allegato all'inizio di questo thread.
Mi risultano poco chiare le caratteristiche che dovrebbero avere i campi:

• Piano di implementazione (potrebbe essere una lista delle attività oppure un riferimento a una modifica tecnica gestita mediante la sezione dei Task)
• • Piano di implementazione  (risorse impiegate, stima delle ore per ogni risorsa)
• Tempo stimato di progetto (data termine improvement considerando il rilascio in produzione, eventuali date di step intermedi)  Validazione prototipo 2 Aprile , validazione preserie 30 Aprile, produzione 15 Maggio

ti proporrei questo approccio: 
aggiungere al model 'Improvement' i campi 'content'  e 'attachments'  analoghi ai 
corrispondenti campi dei modelli 'Task' e 'Claim' ed usare quelli per gli scopi di:
'Piano di implementazione', 'Piano di implementazione', 'Tempo stimato di progetto' 

ti sembra percorribile?

Ciao, Giovanni.

**Comment by fgalfa** [comment]
Si è convenuto di aggiungere un byte nella risposta a QUERY con un numero di versione del protocollo usato, visto che risulta impraticabile cambiare il versionamento del bootloader come proposto. Nel caso del "bootloader 2.0" questo parametro assume valore 1.

**Comment by fgalfa** [comment]
Modifica integrata su bootloader commit f78feb452c8e09ccbcbff6a467a199b9a80e6bbc. Ad ora la lettura avviene eslcusivamente tramite comando QUERY.
