### ISSUE TITLE
Eliminazione del campo "Boot Protocol Version" prima della versione del Boot di ogni Slave nel comando "BOOT_VERSIONS"  

### ISSUE THREAD

**Issue by micheleabelli** [alfa-sw/sw-programmazione-schede#26]
Dato che il protocollo di comunicazione in uso limita a 215 il numero massimo di bytes del payload,
per consentire la corretta trasmissione delle versioni di Boot Loader di tutte le possibili Slave nella risposta al comando "BOOT_VERSIONS" = 119 , è stato necessario eliminare per ogni Slave il campo "Boot Protocol Version", 1 byte, che precede la versione di Boot.
Il campo "Boot Protocol Version" associato alla versione di Boot della scheda Master (MAB o MMT) è rimasto inalterato. 
Il json schema dei 3 rami è stato modificato:
                "boot_master_protocol" : {"type": "number", "propertyOrder":  1, 'fmt': '1s'}, 
                "boot_master"          : {"type": "number", "propertyOrder":  2, 'fmt': '3s'}, 
                "boot_slaves_protocol_version" : {"type": "array",   "propertyOrder":  3, 'fmt': '144s', 'description': "a sequence of 3*48 bytes coding the 3-bytes boot loader fw version running on the 48 slave boards."}, 

Lo stesso campo, con il medesimo significato è già presente nel Bootloader MAB o MMT in risposta al comando USB 'QUERY', ed è qui che occorre usare questa informazione per capire se il Boot Slave supporta o meno l'attività di FW update

**Comment by fgalfa** [comment]
il testing ho mostrato che i campi non sono formattati correttamente

**Comment by micheleabelli** [comment]
Problema sistemato
