### ISSUE TITLE
Fallimento FW Update su CT3.0 con SW aggiornamento su scheda Linux

### ISSUE THREAD

**Issue by micheleabelli** [alfa-sw/sw-programmazione-schede#29]
Quando il SW di aggiornamento FW risiede sulla scheda Linux della macchina CT3.0,
sono emersi problemi nella connessione /sconnessione al bus USB, tali da provocare ad es. il fallimento della procedura di aggiornamento automatica.
Questi problemi non si verificano quando lo stesso SW è installato su Windows, oppure sulla scheda Raspberry.
Osservando i log si vede che dopo l'aggiornamento della scheda MASTER (MAB) si verifica quanto segue:
--------------------------------------------------------------------------------------------------------------------
Read data: 07 E8 A7 02 00 30 00 00 00 00 00 00 00 00 00 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00 FF FF FF 00
Calculated checksum is 37979
Writing data: 06 5B 94 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
Writing data: 02 82 14 2A 5D 6F 9A 25 01 FF
Read data: 02 38 02 01 00 2C 00 00 00 7C 02 00 FF 01 01 00 02 00 5B 94 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Response to QUERY, address = 11264, length = 162816, proto_ver = 1, boot_ver = (1, 0, 2) boot_status = 0 digest = 37979
disconnecting USB
disconnecting USB
programs steps: {1: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 2: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 3: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 4: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 5: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 9: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 10: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 11: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 12: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 13: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 14: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 15: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 16: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 17: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 18: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 19: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 20: {'board-name': 'sccb pompe', 'filename': 'pump-r1-siboot-dipswitch.hex', 'addresses': [1, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 33: {'board-name': 'sccb asse  X', 'filename': 'axis-x-r1-siboot-dipswitch.hex', 'addresses': [33], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 34: {'board-name': 'sccb asse  Y', 'filename': 'axis-y-r1-siboot-dipswitch.hex', 'addresses': [34], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 35: {'board-name': 'sccb magazzini barattoli', 'filename': 'container-r1-siboot-dipswitch.hex', 'addresses': [35, 36, 37, 38], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 36: {'board-name': 'sccb magazzini barattoli', 'filename': 'container-r1-siboot-dipswitch.hex', 'addresses': [35, 36, 37, 38], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 37: {'board-name': 'sccb magazzini barattoli', 'filename': 'container-r1-siboot-dipswitch.hex', 'addresses': [35, 36, 37, 38], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 38: {'board-name': 'sccb magazzini barattoli', 'filename': 'container-r1-siboot-dipswitch.hex', 'addresses': [35, 36, 37, 38], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 39: {'board-name': 'sccb tappature', 'filename': 'cover-r1-siboot-dipswitch.hex', 'addresses': [39, 40], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 40: {'board-name': 'sccb tappature', 'filename': 'cover-r1-siboot-dipswitch.hex', 'addresses': [39, 40], 'version': '4.2.0', 'boot-version-requisite': '1.5.2', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}, 44: {'board-name': 'mmt mixer', 'filename': 'Mixer_boot.X.production.hex', 'addresses': [44], 'version': '5.2.0', 'boot-version-requisite': '1.8.3', 'release-date': datetime.date(2021, 12, 15), 'checksum': 0}}
usb_args: {'deviceId': 1, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
Writing data: 02 82 14 2A 5D 6F 9A 25 01 00
USB connection failed: [Errno 110] Operation timed out
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 2, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 3, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 4, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 5, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 9, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 10, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 11, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 12, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 13, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 14, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 15, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 16, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 17, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 18, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 19, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 20, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 33, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 34, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 35, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 36, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 37, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 38, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 39, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 40, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 44, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
usb_args: {'deviceId': 44, 'cmdRetries': 0, 'cmdTimeout': 15000}
failed to detach kernel driver
USB connection failed: [Errno 16] Resource busy
failed to detach kernel driver
disconnecting USB
executing supervisorctl start alfa_dispatcher dispatcher_alfadesk dispatcher_admin
command done
Update finished

**Comment by fgalfa** [comment]
Si tratta di un problema potenzialmente difficile da risolvere, perché legato al comportamento dello stack USB peculiari di questa macchina. Il problema qui si verifica in fase di disconnessione/connessione della USB ed è dovuto a una non corretta deallocazione delle risorse. Probabilmente c'è da aggiungere un delay tra le due operazioni.

**Comment by fgalfa** [comment]
Nel momento in cui compare l'errore 110 - Operation timeout compare il seguente messaggio da kernel:

```
[ 5133.773932] usb 1-4: usbfs: interface 0 claimed by usbfs while 'alfa_fw_upgrade' sets config #1 
```
Questo messaggio si ripete ogni volta che si tenta di accedere di nuovo alla porta usb.

Un workaround per riprendere le operazioni consiste nel dare il comando:

```
echo 0 > /sys/bus/usb/devices/1-4/bConfigurationValue
```
