### ISSUE TITLE
[bootloader 2.0] reset USB non completo dopo salto ad applicativo

### ISSUE THREAD

**Issue by fgalfa** [alfa-sw/sw-programmazione-schede#3]
Anche dopo l'avvio dell'applicativo, il dispositivo USB HID bootloader è disponibile anche quando l'applicativo gira ma non è possibile nessuna interazione via USB.

**Comment by micheleabelli** [comment]
Modificato il Bootloader 2.0 in modo che prima di effettuare il salto all'applicativo 
il modulo USB e il suo circuito di funzionamento vengano disabilitati (device detached)

**Comment by fgalfa** [comment]
Confermo che il nuovo bootloader si comporta come descritto. Ora è possibile eseguire la procedura anche su macchina virtuale.
