### ISSUE TITLE
[bootloader 2.0] gestione non corretta del reset USB

### ISSUE THREAD

**Issue by fgalfa** [alfa-sw/sw-programmazione-schede#6]
In caso di scollegamento del cavo o di invio del comando di reset USB il bootloader smette di funzionare. Il fatto si manifesta solo con bootloader 2.0.
Scrivo questa issue serve per tenere traccia del fenomeno. Non è un problema prioritario, in quanto con una modifica al programma (commit c52747ab8) la procedura funziona correttamente.

**Comment by fgalfa** [comment]
Riapro la issue in quanto è venuto fuori che, in caso di reset fisico o virtuale del device USB si verifica un salto all'applicativo. Questa situazione crea problemi nella situazione in cui un driver viene disattivato o reinstallato o in cui il driver stesso fa un reset. Tali situazioni si verificano sovente su sistemi windows.

**Comment by micheleabelli** [comment]
Problema sistemato con l'ultima versione di Boot MAB e MMT (MASTER)
